### ISSUE TITLE
Sub-second precision in SM4

### ISSUE THREAD

**Issue by elisagirola** [QutEcoacoustics/emu#330]
I am using Emu to extract metadata from SM4 recordings. Sub-second precision in the timestamp is causing problems. 
![image](https://user-images.githubusercontent.com/90581811/221761215-26fc66ff-8f22-4df5-b02c-592824f6834a.png)
![image](https://user-images.githubusercontent.com/90581811/221761302-f9ffcc14-3c22-4f2e-913e-e5f146f9f548.png)

**Comment by atruskie** [comment]
Available in the [7.0.0 release](https://github.com/QutEcoacoustics/emu/releases/tag/7.0.0).
