### ISSUE TITLE
Extracting sensitivity and gain for SM4

### ISSUE THREAD

**Issue by elisagirola** [QutEcoacoustics/emu#331]
SM4 recorders save information about the gain
![image](https://user-images.githubusercontent.com/90581811/221764234-2d25d6d1-73b2-4899-8510-6e13af2e72d5.png)
it would be good to extract this information. 

Pelase note that:

1) the value 42.2 is similar to the sum of the Gain (16) and Preamp (26) values that can be seen when opening the file with Kaleidoscope. But I cannot tell whether that's just a coincidence or what the 0.2 difference mean
![image](https://user-images.githubusercontent.com/90581811/221764880-8ba4d450-22d0-4655-87d1-737fce95ed86.png)

2) In the first part of the wamd chunk there is a value of 45.2 that could also refer to a gain
![image](https://user-images.githubusercontent.com/90581811/221765085-b3d0cd7f-9010-4ef4-ba9f-cd49201ea818.png)

3) According to the manufacturer, the sensitivity for the SM4 is -35±4dB (0dB=1V/Pa at 1kHz). I cannot see it in the wamd chunk. 

4) As far as I know the Song Meters have both a manual and a digital gain. But I don't know what the values in the wamd chunk refer to. 

Thanks

**Comment by atruskie** [comment]
Yeah so, I looked at this, I'm part way through extracting the values, but there are still some questions. 

There are also different values in the `guano` block. WA publishes the meaning of these fields here: https://www.wildlifeacoustics.com/SCHEMA/GUANO.html

so from what I can see there is:

- microphone sensitivity in the `wamd` block: `45.2 dBFS`
- there is a `gain` value in the `guano` block: `42.2 dB`
   - I believe this is the total gain of `16 dB`  software gain and `26 dB` of preamp gain

**Comment by atruskie** [comment]
Available in the [7.0.0 release](https://github.com/QutEcoacoustics/emu/releases/tag/7.0.0).
