### ISSUE TITLE
Detect and handle/fix faulty audio recording files

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/emu#82]
There are some types of faults which occur in audio recording files which can be consistently and accurately detected. These scenarios should be handled by either ignoring the file, or attempting to fix the problem if possible. Some example fault can be found here:

Empty audio files:
[Empty Files.zip](https://github.com/QutEcoacoustics/emu/files/7707764/Empty.Files.zip)

File with obviously wrong recording date:
[1970.Audio.File.zip](https://github.com/QutEcoacoustics/emu/files/7707780/1970.Audio.File.zip)

**Comment by atruskie** [comment]
Note both of these files are from AudioMoths

**Comment by atruskie** [comment]
Closing in favor of: https://github.com/QutEcoacoustics/emu/issues/226
